Repository appsignal/appsignal-elixir, pull requests merged in 2018-06, with the labels that each got.

#360 Add appsignal_to_json implementation
  c_src/appsignal_extension.c
  config/config.exs
  lib/appsignal/nif.ex
  lib/appsignal/transaction.ex
  test/appsignal/release_upgrade_test.exs
  test/appsignal/transaction_test.exs
Labels: chore

#359 Use :hackney instead of cURL to download agent
  mix.exs
  mix_helpers.exs
Labels: enhancement

#356 Allow calling `Transaction.register/1` and `Transaction.complete/1` when the Registry is not alive
  lib/appsignal/transaction.ex
  lib/appsignal/transaction/registry.ex
  test/appsignal/transaction/registry_test.exs
  test/appsignal/transaction_test.exs
Labels: bug

#353 Improve memory reporting for container systems
  CHANGELOG.md
  agent.exs
  mix.exs
Labels: feature

#361 Add Appsignal.Transaction.set_namespace/1-2
  c_src/appsignal_extension.c
  lib/appsignal/nif.ex
  lib/appsignal/transaction.ex
  test/appsignal/transaction_test.exs
Labels: enhancement
