Repository appsignal/appsignal-elixir, pull requests merged in 2018-07, with the labels that each got.

#370 Bump agent to v-e801925
  agent.exs
Labels: bug

#382 Use gmake over make when gmake executable exists
  mix_helpers.exs
Labels: enhancement

#384 Support doubles in extension
  agent.exs
  c_src/appsignal_extension.c
  lib/appsignal.ex
  test/appsignal/appsignal_test.exs
Labels: chore

#386 Fix test failure and warnings on Elixir 1.7
  .travis.yml
  lib/appsignal.ex
  lib/appsignal/demo.ex
  lib/appsignal/plug.ex
  test/appsignal/error_handler/error_matcher_test.exs
Labels: chore

#363 Add working_directory_path config option
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
Labels: enhancement
