Repository appsignal/appsignal-elixir, pull requests merged in 2018-10, with the labels that each got.

#402 Create separate modules for testing Appsignal.Phoenix.Channel
  test/phoenix/channel_test.exs
Labels: bug

#403 Add :hackney to :applications
  mix.exs
Labels: bug

#404 Add :poison to :applications
  mix.exs
Labels: bug

#405 Remove unused extension send_params option
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
Labels: chore

#407 Create separate modules for testing Appsignal.Phoenix.Channel
  test/phoenix/channel_test.exs
Labels: chore

#406 Link gcc to extension .so library
  Makefile
Labels: bug

#408 Pretty print lists in diagnose output
  lib/mix/tasks/appsignal.diagnose.ex
  test/mix/tasks/appsignal_diagnose_test.exs
Labels: bug

#399 Use `Mix.shell.info` instead of `Logger.info` in mix helpers
  mix_helpers.exs
Labels: bug

#412 Add new agent & extension diagnose report keys
  agent.exs
  lib/appsignal/diagnose/agent.ex
  lib/appsignal/system.ex
  test/mix/tasks/appsignal_diagnose_test.exs
Labels: enhancement

#414 Add diagnose command --[no-]send-report option
  lib/mix/tasks/appsignal.diagnose.ex
  test/mix/tasks/appsignal_diagnose_test.exs
Labels: enhancement
