Repository appsignal/appsignal-elixir, pull requests merged in 2018-05, with the labels that each got.

#339 Remove default hostname
  agent.exs
  lib/appsignal/config.ex
  lib/appsignal/system.ex
  test/appsignal/config_test.exs
  test/appsignal/diagnose/report_test.exs
  test/appsignal/release_upgrade_test.exs
  test/appsignal/system_test.exs
  test/support/fake_system.ex
Labels: chore

#340 Log with :info level instead of :warn when AppSignal is disabled
  lib/appsignal.ex
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
Labels: enhancement

#343 Add filter_session_data config option
  lib/appsignal/config.ex
  lib/appsignal/phoenix/channel.ex
  lib/appsignal/plug.ex
  lib/appsignal/transaction.ex
  lib/appsignal/utils/map_filter.ex
  test/appsignal/config_test.exs
  test/appsignal/transaction/filter_test.exs
  test/appsignal/transaction_test.exs
  test/phoenix/transaction/filter_test.exs
Labels: feature

#336 Explicit header whitelist in configuration
  lib/appsignal/config.ex
  lib/mix/tasks/appsignal.install.ex
  test/mix/tasks/appsignal_install_test.exs
Labels: feature

#347 Bump agent to e509c90
  agent.exs
Labels: bug

#350 Merge instead of ignore Phoenix's :filter_parameters if also configured in AppSignal
  lib/appsignal/utils/params_filter.ex
  test/appsignal/transaction/filter_test.exs
Labels: bug

#351 Remove script_name, query_string and peer from Plug.extract_sample_data/1
  lib/appsignal/plug.ex
  test/appsignal/appsignal_test.exs
  test/appsignal/plug_test.exs
Labels: bug

#344 Use hackney instead of HTTPoison
  lib/appsignal/diagnose/report.ex
  lib/appsignal/utils/push_api_key_validator.ex
  mix.exs
Labels: chore, enhancement
