Repository appsignal/appsignal-elixir, pull requests merged in 2018-04, with the labels that each got.

#324 Allow OTP 18.3 failures
  .travis.yml
Labels: chore

#322 Relax :httpoison dependency to allow ~> 1.0
  mix.exs
Labels: enhancement

#329 Remove transaction when calling `Transaction.complete`
  lib/appsignal/demo.ex
  lib/appsignal/transaction.ex
  test/appsignal/demo_test.exs
  test/appsignal/transaction_test.exs
  test/support/fake_demo.ex
Labels: enhancement

#332 Hard-remove transactions from the Registry
  lib/appsignal/transaction.ex
  lib/appsignal/transaction/registry.ex
  test/appsignal/transaction/registry_test.exs
Labels: enhancement

#330 Don't register Transactions created by `Appsignal.send_error/7`
  lib/appsignal.ex
  lib/appsignal/nif.ex
  lib/appsignal/transaction.ex
  test/appsignal/appsignal_test.exs
  test/appsignal/nif_test.exs
  test/appsignal/transaction_test.exs
  test/support/utils.ex
Labels: enhancement

#331 Accept tags for (custom) metrics
  agent.exs
  c_src/appsignal_extension.c
  lib/appsignal.ex
  lib/appsignal/nif.ex
  test/appsignal/appsignal_test.exs
Labels: enhancement

#333 Demonitor processes when the transaction completes
  lib/appsignal/transaction/registry.ex
  test/appsignal/transaction/registry_test.exs
Labels: bug
