Repository appsignal/appsignal-elixir, pull requests merged in 2019-01, with the labels that each got.

#436 Document how to attach to new telemetry versions.
  lib/appsignal/ecto.ex
Labels: chore

#438 Get tests to pass on Elixir 1.8
  lib/appsignal/diagnose/paths.ex
  test/appsignal/config_test.exs
  test/appsignal/error_handler/error_matcher_test.exs
Labels: chore

#437 Drop Mock dependency, use FakeTransaction, FakeSystem and Transaction.to_map/1 instead
  lib/appsignal/demo.ex
  lib/appsignal/instrumentation/decorators.ex
  lib/appsignal/instrumentation/helpers.ex
  mix.exs
  mix_helpers.exs
  test/appsignal/demo_test.exs
  test/appsignal/instrumentation/decorator_test.exs
  test/appsignal/instrumentation/helpers_test.exs
  test/appsignal/transaction_test.exs
  test/mix/helpers_test.exs
  test/support/appsignal/fake_demo.ex
  test/support/appsignal/fake_diagnose_report.ex
  test/support/appsignal/fake_nif.ex
  test/support/appsignal/fake_system.ex
  test/support/appsignal/fake_transaction.ex
  test/support/fake_system.ex
Labels: chore

#441 Recommend "prod" instead of "production" in installer
  lib/mix/tasks/appsignal.install.ex
  test/appsignal/diagnose/report_test.exs
  test/mix/tasks/appsignal_install_test.exs
Labels: chore

#448 Block on ignoring pids in TransactionRegistry
  lib/appsignal/transaction/registry.ex
  test/appsignal/transaction/registry_test.exs
Labels: bug

#452 Add response status codes to Plug samples
  lib/appsignal/plug.ex
  test/appsignal/plug_test.exs
Labels: enhancement, requests

#450 Fix tests for test_no_nif test environment
  .travis.yml
  lib/mix/tasks/appsignal.diagnose.ex
  test/mix/tasks/appsignal_diagnose_test.exs
Labels: chore
