Repository appsignal/appsignal-elixir, pull requests merged in 2019-09, with the labels that each got.

#506 Add support for both Jason and Poison
  lib/appsignal/diagnose/agent.ex
  lib/appsignal/diagnose/report.ex
  lib/appsignal/json.ex
  lib/appsignal/transaction.ex
  lib/mix/tasks/appsignal.diagnose.ex
  mix.exs
  mix_helpers.exs
Labels: enhancement

#516 hackney workaround for honor_cipher_order
  lib/appsignal/transmitter.ex
  mix_helpers.exs
  test/appsignal/transmitter_test.exs
Labels: bug

#513 Ensure all report values are strings
  mix_helpers.exs
Labels: bug

#507 Filter structs in MapFilter
  lib/appsignal/utils/map_filter.ex
  test/appsignal/transaction/filter_test.exs
Labels: enhancement

#492 Add Erlang Run Queue length metric
  lib/appsignal/probes/erlang_probe.ex
  test/appsignal/probes/erlang_probe_test.exs
Labels: chore
