Repository appsignal/appsignal-elixir, pull requests merged in 2019-02, with the labels that each got.

#451 Fail AppSignal extension installation on warnings
  Makefile
  lib/appsignal/diagnose/paths.ex
  lib/appsignal/nif.ex
  mix_helpers.exs
  test/mix/tasks/appsignal_diagnose_test.exs
Labels: bug

#453 Add response status codes to Plug samples
  lib/appsignal/plug.ex
  test/appsignal/plug_test.exs
Labels: enhancement, requests

#455 Fix Credo warnings and run Credo on CI
  .credo.exs
  .travis.yml
  lib/appsignal.ex
  lib/appsignal/config.ex
  lib/appsignal/demo.ex
  lib/appsignal/diagnose/config.ex
  lib/appsignal/diagnose/paths.ex
  lib/appsignal/error.ex
  lib/appsignal/error_handler.ex
  lib/appsignal/instrumentation/decorators.ex
  lib/appsignal/nif.ex
  lib/appsignal/phoenix.ex
  lib/appsignal/phoenix/channel.ex
  lib/appsignal/plug.ex
  lib/appsignal/transaction.ex
  lib/mix/tasks/appsignal.install.ex
  mix.exs
  mix_helpers.exs
  scripts/credo
  test/appsignal/appsignal_test.exs
  test/appsignal/config_test.exs
  test/appsignal/diagnose/report_test.exs
  test/appsignal/error_handler_test.exs
  test/appsignal/instrumentation/helpers_test.exs
  test/appsignal/transmitter_test.exs
  test/appsignal/utils/data_encoder_test.exs
  test/mix/tasks/appsignal_diagnose_test.exs
  test/mix/tasks/appsignal_install_test.exs
  test/phoenix/instrumenter_test.exs
  test/support/appsignal/fake_transaction.ex
Labels: chore

#454 Use :logger instead of :error_logger on OTP >= 21
  lib/appsignal.ex
  lib/appsignal/error_handler.ex
  lib/appsignal/error_logger_handler.ex
  lib/appsignal/logger_handler.ex
  test/appsignal/error_handler_test.exs
  test/appsignal/error_logger_handler_test.exs
  test/appsignal/logger_handler_test.exs
Labels: chore

#456 Support send_params option
  lib/appsignal/config.ex
  lib/appsignal/transaction.ex
  test/appsignal/config_test.exs
  test/appsignal/transaction_test.exs
Labels: feature
