Repository appsignal/appsignal-elixir, pull requests merged in 2019-05, with the labels that each got.

#485 Update make clean task
  Makefile
  scripts/test
Labels: chore, dev happiness

#486 Handle :ignored Transactions in Transaction and Instrumentation.Helpers
  .travis.yml
  lib/appsignal/instrumentation/helpers.ex
  lib/appsignal/transaction.ex
  scripts/run_formatter
  test/appsignal/instrumentation/helpers_test.exs
  test/appsignal/transaction_test.exs
Labels: enhancement

#488 Fix FreeBSD fatal warnings linking flag
  Makefile
Labels: bug

#487 ldd version error handling
  mix_helpers.exs
  test/mix/helpers_test.exs
Labels: enhancement

#484 Fix FreeBSD compilation
  Makefile
Labels: bug

#491 Use the bundled certificate and ciphers when downloading agent
  mix_helpers.exs
Labels: enhancement
