Repository appsignal/appsignal-elixir, pull requests merged in 2019-04, with the labels that each got.

#475 Handle atom keys in MapFilter.filter_values/2
  lib/appsignal/utils/map_filter.ex
  test/appsignal/transaction/filter_test.exs
Labels: bug

#480 Implicitly check ignored transactions in `TransactionRegistry.lookup/1`
  lib/appsignal/error_handler.ex
  lib/appsignal/transaction.ex
  lib/appsignal/transaction/registry.ex
  test/appsignal/plug_test.exs
  test/appsignal/transaction/registry_test.exs
  test/support/appsignal/fake_transaction.ex
Labels: enhancement

#481 Convert time units for all Ecto callbacks
  lib/appsignal/ecto.ex
  test/appsignal/ecto_test.exs
Labels: enhancement

#478 Deactivate AppSignal when not active
  lib/appsignal/demo.ex
  lib/appsignal/ecto.ex
  lib/appsignal/phoenix/instrumenter.ex
  lib/appsignal/plug.ex
  lib/appsignal/transaction.ex
  lib/appsignal/transaction/registry.ex
  lib/mix/tasks/appsignal.demo.ex
  test/appsignal/ecto_test.exs
  test/appsignal/plug_test.exs
  test/appsignal/transaction/registry_test.exs
  test/appsignal/transaction_test.exs
  test/phoenix/instrumenter_test.exs
Labels: enhancement

#479 Handle errors in Mix.Appsignal.Helper.uid/0
  mix_helpers.exs
  test/mix/helpers_test.exs
  test/support/fake_system.ex
Labels: bug

#482 Do not build every branch automatically
  .travis.yml
Labels: chore
