Repository appsignal/appsignal-elixir, pull requests merged in 2019-03, with the labels that each got.

#459 Update Ecto integration to support both Telemetry 0.3.x and 0.4.x
  lib/appsignal/ecto.ex
  test/appsignal/ecto_test.exs
  test/support/fake_transaction.ex
Labels: feature

#464 Allow Appsignal.Plug.call/2 to be overridden
  lib/appsignal/plug.ex
  test/appsignal/plug_test.exs
Labels: chore

#461 Minutly Probing for Custom Metrics
  lib/appsignal.ex
  lib/appsignal/probes/probes.ex
  test/appsignal/probes/probes_test.exs
  test/support/fake_probe.ex
Labels: feature

#466 Add Erlang Probe
  config/config.exs
  lib/appsignal.ex
  lib/appsignal/probes/erlang_probe.ex
  test/appsignal/probes/erlang_probe_test.exs
  test/support/appsignal/fake_appsignal.ex
  test/support/fake_probe.ex
  test/support/test_agent.ex
Labels: feature

#467 Wrap System.stacktrace() in try/catch block in Transaction tests
  test/appsignal/transaction_test.exs
Labels: chore

#468 Make sure events are added to transactions started with decorators
  lib/appsignal/instrumentation/decorators.ex
  test/appsignal/instrumentation/decorator_test.exs
Labels: bug

#470 Add enable_minutely_probes config option
  lib/appsignal/config.ex
  lib/appsignal/probes/probes.ex
  test/appsignal/config_test.exs
  test/appsignal/probes/probes_test.exs
Labels: enhancement

#469 Set extra tags erlang
  config/config.exs
  lib/appsignal/probes/erlang_probe.ex
  test/appsignal/probes/erlang_probe_test.exs
  test/support/fake_inet.ex
Labels: bug

#471 Don't use fetch_env!/2 in ErlangProbe
  lib/appsignal/probes/erlang_probe.ex
  test/appsignal/probes/erlang_probe_test.exs
Labels: chore

#465 Add script to run all tests locally
  .travis.yml
  scripts/check_warnings
  scripts/credo
  scripts/run_formatter
  scripts/test
Labels: chore, dev happiness

#472 Remove sleeps from tests
  test/appsignal/error_handler/error_matcher_test.exs
  test/appsignal/error_handler_test.exs
  test/appsignal/error_logger_handler_test.exs
  test/appsignal/instrumentation/helpers_test.exs
  test/appsignal/logger_handler_test.exs
  test/appsignal/plug_test.exs
  test/appsignal/probes/probes_test.exs
  test/support/utils.ex
Labels: chore

#473 Bump agent to d8dc806
  agent.exs
Labels: feature
