Repository appsignal/appsignal-elixir, pull requests merged in 2020-12, with the labels that each got.

#599 Add register stub to deprecated transaction registry
  lib/appsignal/transaction_registry.ex
Labels: chore

#600 Don't register query spans without parents
  lib/appsignal/ecto.ex
  test/appsignal/ecto_test.exs
Labels: bug

#607 Switch to reference-based child Span API
  agent.exs
  c_src/appsignal_extension.c
  lib/appsignal/nif.ex
  lib/appsignal/span.ex
  test/appsignal/nif_test.exs
  test/appsignal/span_test.exs
  test/appsignal/tracer_test.exs
  test/support/appsignal/test_nif.ex
Labels: enhancement

#608 Monitor all registered spans
  lib/appsignal/monitor.ex
  lib/appsignal/tracer.ex
  test/appsignal/appsignal_test.exs
  test/appsignal/demo_test.exs
  test/appsignal/ecto_test.exs
  test/appsignal/instrumentation_test.exs
  test/appsignal/monitor_test.exs
  test/appsignal/tracer_test.exs
  test/mix/tasks/appsignal_install_test.exs
Labels: enhancement
