Repository appsignal/appsignal-elixir, pull requests merged in 2021-01, with the labels that each got.

#611 Let set error use root span
  lib/appsignal/instrumentation.ex
  test/appsignal/instrumentation_test.exs
Labels: bug

#620 Pass Elixir exceptions to `Appsignal.Instrumentation.se(t|nd)_error/2`
  lib/appsignal/error.ex
  lib/appsignal/instrumentation.ex
  lib/appsignal/span.ex
  lib/appsignal/test/span.ex
  test/appsignal/error_test.exs
  test/appsignal/instrumentation_test.exs
  test/appsignal/span_test.exs
Labels: feature

#623 Clear warnings
  .semaphore/semaphore.yml
  lib/appsignal.ex
  lib/appsignal/instrumentation/helpers.ex
  lib/appsignal/monitor.ex
  lib/appsignal/probes/probes.ex
  lib/appsignal/tracer.ex
Labels: bug

#626 Probes.handle_info/2 handles non-exception errors
  lib/appsignal/probes/probes.ex
  test/appsignal/probes/probes_test.exs
  test/support/fake_probe.ex
Labels: bug

#629 Make sure Appsignal.se(nd|t)_error is properly delegated
  lib/appsignal.ex
  test/appsignal/appsignal_test.exs
Labels: bug

#628 Update logo to new design
  logo.png
Labels: chore, design

#631 Use pid from conn in Error.Backend if available
  lib/appsignal/error/backend.ex
  test/appsignal/error/backend_test.exs
Labels: bug
