Repository appsignal/appsignal-elixir, pull requests merged in 2021-06, with the labels that each got.

#650 Replacing AppSignal.Monitor's list state with a MapSet
  lib/appsignal/monitor.ex
  test/appsignal/monitor_test.exs
Labels: enhancement

#651 Track erlang atom metrics
  lib/appsignal/probes/erlang_probe.ex
  test/appsignal/probes/erlang_probe_test.exs
Labels: enhancement

#653 Update APPSIGNAL_BUILD_FOR_MUSL flag behavior
  .changesets/musl-flag.md
  mix_helpers.exs
  test/mix/helpers_test.exs
Labels: chore

#654 Add Linux ARM flag to enable experimental build
  .changesets/linux-arm-build.md
  agent.exs
  mix_helpers.exs
  test/mix/helpers_test.exs
Labels: feature

#656 Add Linux ARM flag to enable experimental build
  .changesets/linux-arm-build.md
  agent.exs
  mix_helpers.exs
  test/mix/helpers_test.exs
Labels: feature

#655 Add mono to project
  CHANGELOG.md
  README.md
  mono.yml
  script/setup
Labels: chore

#657 Add Linux ARM override value to diagnose report
  .changesets/.gitkeep
  .changesets/add-linux-arm-override-to-diagnose-report.md
  lib/mix/tasks/appsignal.diagnose.ex
  mix_helpers.exs
  test/mix/tasks/appsignal_diagnose_test.exs
Labels: bug
