Repository appsignal/appsignal-elixir, pull requests merged in 2021-11, with the labels that each got.

#703 Bump agent to 09308fb
  .changesets/bump-agent-to-09308fb.md
  agent.exs
Labels: enhancement

#702 source_ref needs 'v' prepended since tagging now has 'v' prepended
  mix.exs
Labels: bug

#704 Update `credo` to version 1.5.6
  lib/appsignal/demo.ex
  lib/appsignal/diagnose/agent.ex
  lib/appsignal/diagnose/host.ex
  lib/appsignal/diagnose/library.ex
  lib/appsignal/ecto.ex
  lib/appsignal/error/backend.ex
  lib/appsignal/instrumentation.ex
  lib/appsignal/instrumentation/decorators.ex
  lib/appsignal/logger.ex
  lib/appsignal/monitor.ex
  lib/appsignal/probes/erlang_probe.ex
  lib/appsignal/span.ex
  lib/appsignal/tracer.ex
  lib/appsignal/utils.ex
  lib/mix/tasks/appsignal.diagnose.ex
  mix.exs
  mix_helpers.exs
  test/support/test_agent.ex
Labels: chore

#712 Update Elixir master to main
  .semaphore/semaphore.yml
  bin/setup
Labels: chore

#710 Implement scheduler utilization metric
  .changesets/add-scheduler-utilization-to-minutely-probes.md
  lib/appsignal.ex
  lib/appsignal/probes/erlang_probe.ex
  lib/appsignal/probes/probes.ex
  mix.exs
  test/appsignal/probes/erlang_probe_test.exs
  test/appsignal/probes/probes_test.exs
  test/support/fake_probe.ex
Labels: enhancement

#721 Don't consider config valid if API key is empty
  .changesets/push-api-key-as-an-empty-string-is-not-considered-valid-anymore.md
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
Labels: bug

#716 Use only supported TLS versions
  .changesets/fix-agent-download-openssl-below-111.md
  lib/appsignal/transmitter.ex
  mix_helpers.exs
Labels: bug

#723 Fix meaningless scheduler utilization values
  lib/appsignal.ex
  lib/appsignal/probes/erlang_probe.ex
Labels: bug

#718 Fix Erlang/OTP version usage in CI
  .semaphore/semaphore.yml
  bin/setup
  dialyzer.ignore-warnings
Labels: bug, dev happiness

#731 Sort config options alphabetically
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
Labels: chore

#730 Remove unused allocation tracking config option
  .changesets/remove-unused-allocation-tracking-config-option.md
  lib/appsignal/config.ex
Labels: chore

#729 Fix Phoenix parameter filtering
  .changesets/fix-phoenix-filter-parameters.md
  lib/appsignal/span.ex
Labels: bug
