Repository appsignal/appsignal-elixir, pull requests merged in 2021-08, with the labels that each got.

#662 Fix Apple ARM detection
  .changesets/apple-arm-detection.md
  mix_helpers.exs
Labels: bug

#663 Bump agent to 0f40689
  .changesets/bump-agent-to-0f40689.md
  agent.exs
Labels: chore

#664 Upgrade telemetry dependency
  .changesets/add-support-for-telemetry-1-0-0.md
  mix.exs
Labels: chore

#666 Add explicit mime dependency for Elixir < 1.10
  mix.exs
Labels: chore

#667 Update Elixir 1.11 and Erlang 23 versions on CI
  .semaphore/semaphore.yml
Labels: chore

#668 Add OTP 24 to CI
  .semaphore/semaphore.yml
Labels: chore

#669 Add Elixir 1.12.2 to CI
  .semaphore/semaphore.yml
Labels: chore

#665 Replace decorator slashes with underscores
  .changesets/use-underscores-instead-of-slashes-in-spans-created-from-decorators.md
  lib/appsignal/instrumentation/decorators.ex
  test/appsignal/instrumentation_test.exs
Labels: enhancement

#670 Bump to agent 0318770
  .changesets/bump-agent-0318770.md
  agent.exs
Labels: chore
