Repository appsignal/appsignal-elixir, pull requests merged in 2021-07, with the labels that each got.

#658 Bump agent to v-c2024bf
  agent.exs
Labels: bug

#659 Add Git linter to build
  .semaphore/semaphore.yml
  script/install_lintje
Labels: chore, dev happiness

#660 Update agent to v-891c6b0
  .changesets/bump-agent-891c6b0.md
  agent.exs
Labels: chore

#661 Transaction and channel action decorators only create root spans
  .changesets/only-create-root-spans-from-transaction-and-channel-action-decorators.md
  lib/appsignal/instrumentation.ex
  lib/appsignal/instrumentation/decorators.ex
  test/appsignal/instrumentation_test.exs
  test/appsignal/tracer_test.exs
Labels: bug
