Repository appsignal/appsignal-elixir, pull requests merged in 2021-09, with the labels that each got.

#671 Add mirrors to download the agent
  .changesets/add-mirrors-to-download-the-agent.md
  agent.exs
  mix_helpers.exs
Labels: chore

#673 Add Elixir master download on CI
  bin/setup
Labels: bug

#677 Refactor Git lint script
  .semaphore/semaphore.yml
  script/lint_git
Labels: chore, dev happiness

#678 Fix bin/setup script, exit on failure
  bin/setup
Labels: chore, dev happiness

#674 Fix extension installer from tmp cached download
  .changesets/fix-extension-installer-from-cached-source.md
  mix_helpers.exs
Labels: bug

#675 Run mix.format on project
  .semaphore/semaphore.yml
  lib/appsignal/nif.ex
  lib/appsignal/transmitter.ex
  test/appsignal/nif_test.exs
Labels: chore

#680 Speed up function arity check in Appsignal.Instrumentation
  lib/appsignal/instrumentation.ex
Labels: enhancement

#682 Bump agent to 7376537
  .changesets/bump-agent-to-7376537.md
  agent.exs
Labels: enhancement
