Repository appsignal/appsignal-elixir, pull requests merged in 2022-06, with the labels that each got.

#775 Use default log level when AppSignal is not configured
  .changesets/fix-compile-time-error-with-empty-configurations.md
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
  test/support/utils.ex
Labels: bug

#776 Handle empty configurations for all config options
  .changesets/don-t-crash-at-compile-time-when-appsignal-is-not-configured.md
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
Labels: chore

#777 Improve error reporting on extension load failure
  .changesets/improve-error-message-on-extension-load-failure.md
  config/config.exs
  dialyzer.ignore-warnings
  lib/appsignal.ex
  mix_helpers.exs
  test/appsignal/appsignal_test.exs
  test/support/fake_os.ex
Labels: enhancement

#778 Bump agent to v-d573c9b
  .changesets/bump-agent-to-v-d573c9b.md
  agent.exs
Labels: chore
