Repository appsignal/appsignal-elixir, pull requests merged in 2022-01, with the labels that each got.

#745 Add compilation step to CI tests
  .semaphore/semaphore.yml
  mix_helpers.exs
  test/appsignal/nif_test.exs
Labels: enhancement

#744 Change how the agent version is retrieved for diagnose
  .changesets/diagnose-report-now-gets-the-agent-version-from-the-agent-file.md
  lib/appsignal/diagnose/library.ex
  lib/appsignal/nif.ex
  test/appsignal/nif_test.exs
  test/mix/tasks/appsignal_diagnose_test.exs
Labels: bug

#750 Use `log_level` instead of `debug`
  .changesets/use-log-level-config-option-instead-of-debug.md
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
  test/appsignal/logger_test.exs
Labels: bug

#724 Fix OTP 20 tests
  .semaphore/semaphore.yml
  mix.exs
  test/appsignal/error/backend_test.exs
  test/appsignal/transmitter_test.exs
Labels: bug, dev happiness
