Repository appsignal/appsignal-elixir, pull requests merged in 2022-02, with the labels that each got.

#758 Elixir ci 1.13.2
  .semaphore/semaphore.yml
  test/appsignal/error_test.exs
  test/appsignal/span_test.exs
Labels: chore

#760 Don't mock all of :erlang.system_info/1 in tests
  test/support/fake_erlang.ex
Labels: chore

#761 Check CAcert file exists when installing extension
  .changesets/prevent-extension-installation-failure-when-cacert-is-not-accessible.md
  mix_helpers.exs
Labels: bug

#764 Tracer can ignore a specific process
  lib/appsignal/tracer.ex
  test/appsignal/tracer_test.exs
Labels: feature

#765 Bump agent to v-bbc830a
  .changesets/bump-agent-bbc830a.md
  agent.exs
Labels: chore

#767 Bump agent to v-f57e6cb
  .changesets/bump-agent-to-v-f57e6cb.md
  agent.exs
Labels: enhancement
