Repository appsignal/appsignal-elixir, pull requests merged in 2023-06, with the labels that each got.

#848 Add statsd_port config option
  .changesets/bump-agent-to-fd8ee9e.md
  .changesets/statsd-port-config-option.md
  agent.exs
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
Labels: enhancement

#851 Add elixir 1.15 to CI
  .semaphore/semaphore.yml
  .semaphore/versions.rb
  dialyzer.ignore-warnings
  lib/appsignal.ex
  lib/appsignal/absinthe.ex
  lib/appsignal/config.ex
  lib/appsignal/ecto.ex
  lib/appsignal/error/backend.ex
  lib/appsignal/finch.ex
  lib/appsignal/oban.ex
  lib/appsignal/tesla.ex
  lib/appsignal/transmitter.ex
  lib/appsignal/utils.ex
  mix.exs
  mix_helpers.exs
  test/mix/test_helper.exs
Labels: chore

#854 Never register cowboy error reports
  .changesets/add-handling-for-cowboy-error-edge-cases-to-prevent-error-backend-crashes.md
  lib/appsignal/error/backend.ex
  lib/appsignal/stacktrace.ex
  test/appsignal/error/backend_test.exs
  test/appsignal/stacktrace_test.exs
Labels: bug

#856 Reimplement argument cleaning
  lib/appsignal/stacktrace.ex
  lib/appsignal/utils/argument_cleaner.ex
  lib/appsignal/utils/type.ex
  test/appsignal/stacktrace_test.exs
  test/appsignal/utils/argument_cleaner_test.exs
  test/appsignal/utils/type_test.exs
Labels: chore

#855 Reduce number of reductions in Appsignal.Instrumentation.instrument/3
  .changesets/improve-tracer-performance-by-removing-duplicate-runtime-configuration-and-storage-checks.md
  lib/appsignal/config.ex
  lib/appsignal/span.ex
  lib/appsignal/tracer.ex
  test/appsignal/span_test.exs
Labels: enhancement

#849 Add AddressSanitizer test setup
  Dockerfile
  README.md
  c_src/appsignal_extension.c
  spans.exs
Labels: chore
