Repository appsignal/appsignal-elixir, pull requests merged in 2023-04, with the labels that each got.

#835 Explicitly order configuration options in diagnose
  lib/mix/tasks/appsignal.diagnose.ex
Labels: chore

#837 Handle unexpected events in Error.Backend
  .changesets/handle-unexpected-events-in-logger-backend.md
  lib/appsignal/logger/backend.ex
  test/appsignal/error/backend_test.exs
Labels: bug

#838 Update agent to version 6f29190
  .changesets/update-agent-6f29190.md
  agent.exs
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
Labels: enhancement
