Repository appsignal/appsignal-elixir, pull requests merged in 2023-08, with the labels that each got.

#876 Add string cast to agent diagnose
  dialyzer.ignore-warnings
  lib/appsignal/diagnose/agent.ex
Labels: chore

#877 Bump agent to version d789895
  .changesets/bump-agent-d789895.md
  agent.exs
Labels: enhancement

#879 Add host_role config option
  .changesets/add-role-config-option.md
  lib/appsignal/config.ex
  test/appsignal/config_test.exs
Labels: enhancement

#882 Lock Dialyxir to 1.3 for older Elixir versions
  mix.exs
Labels: chore

#884 Bump agent to 6133900
  .changesets/bump-agent-to-6133900.md
  agent.exs
Labels: bug
