Repository appsignal/appsignal-elixir, pull requests merged in 2023-07, with the labels that each got.

#866 Implement `set_sample_data_if_nil` method
  .changesets/add-set-sample-data-if-nil-function.md
  agent.exs
  c_src/appsignal_extension.c
  lib/appsignal/nif.ex
  lib/appsignal/span.ex
  lib/appsignal/test/span.ex
  test/appsignal/span_test.exs
Labels: bug

#867 Add `RENDER_GIT_COMMIT` changeset
  .changesets/use-render_git_commit-as-revision.md
  CHANGELOG.md
Labels: chore

#871 Bump agent to 32590eb
  .changesets/bump-agent-to-32590eb.md
  agent.exs
Labels: enhancement

#870 Allow JSON and Logfmt log messages
  .changesets/allow-json-and-logfmt-log-messages.md
  lib/appsignal/logger.ex
  test/appsignal/logger_test.exs
Labels: enhancement

#873 Remove unneeded _APPSIGNAL_DIAGNOSE env vars
  dialyzer.ignore-warnings
  lib/appsignal/diagnose/agent.ex
Labels: chore

#874 Report total CPU usage host metric for VMs
  .changesets/report-total-cpu-usage-metric-for-vms.md
  agent.exs
Labels: enhancement

#868 Fix atoms in transaction_event decorator
  lib/appsignal/instrumentation/decorators.ex
  test/appsignal/instrumentation_test.exs
Labels: bug

#875 Bump agent to 6bec691
  .changesets/bump-agent-to-6bec691.md
  agent.exs
Labels: enhancement
