Repository appsignal/appsignal-elixir, pull requests merged in 2023-05, with the labels that each got.

#841 Update bundled certificates
  .changesets/update-bundled-trusted-root-certificates-.md
  priv/cacert.pem
Labels: chore

#842 Bump agent to 4a0a036
  .changesets/bump-agent-to-4a0a036.md
  agent.exs
Labels: enhancement

#844 Bump agent to version 6ac961d
  .changesets/trim-sql-attributes-in-spans.md
  agent.exs
Labels: bug

#846 Update agent to v-f9b0c15
  .changesets/update-agent-to-f9b0c15.md
  agent.exs
Labels: chore
