Repository appsignal/appsignal-elixir, pull requests merged in 2024-09, with the labels that each got.

#960 Check-in scheduler
  .changesets/send-check-ins-concurrently.md
  config/config.exs
  lib/appsignal.ex
  lib/appsignal/check_in.ex
  lib/appsignal/check_in/check_in.ex
  lib/appsignal/check_in/cron.ex
  lib/appsignal/check_in/scheduler.ex
  lib/appsignal/diagnose/report.ex
  lib/appsignal/transmitter.ex
  mix_helpers.exs
  test/appsignal/absinthe_test.exs
  test/appsignal/check_in/check_in_test.exs
  test/appsignal/check_in/scheduler_test.exs
  test/appsignal/ecto_repo_test.exs
  test/appsignal/transmitter_test.exs
  test/mix/helpers_test.exs
  test/support/appsignal/fake_debounce.ex
  test/support/appsignal/fake_integration_logger.ex
  test/support/appsignal/fake_scheduler.ex
  test/support/appsignal/fake_transmitter.ex
  test/support/fake_system.ex
  test/support/utils.ex
Labels: enhancement

#961 Remove Transaction Nif code
  c_src/appsignal_extension.c
  lib/appsignal/nif.ex
  test/appsignal/nif_test.exs
Labels: chore

#963 Add agent release workflow
  .github/workflows/agent_release.yml
Labels: dev happiness

#962 Implement heartbeat check-ins
  .changesets/add-heartbeat-check-ins.md
  config/config.exs
  lib/appsignal/check_in/check_in.ex
  lib/appsignal/check_in/cron.ex
  lib/appsignal/check_in/event.ex
  lib/appsignal/check_in/heartbeat.ex
  lib/appsignal/check_in/scheduler.ex
  test/appsignal/check_in/check_in_test.exs
  test/appsignal/check_in/event_test.exs
  test/appsignal/check_in/scheduler_test.exs
  test/support/appsignal/fake_scheduler.ex
Labels: feature

#965 Update config for CI
  .github/workflows/ci.yaml
Labels: chore
