Repository appsignal/appsignal-elixir, pull requests merged in 2024-06, with the labels that each got.

#944 Add set_name_if_nil helper
  .changesets/add-span-set_name_if_nil-helper.md
  agent.exs
  c_src/appsignal_extension.c
  lib/appsignal/nif.ex
  lib/appsignal/span.ex
  lib/appsignal/test/span.ex
  test/appsignal/span_test.exs
  test/support/appsignal/test_nif.ex
Labels: enhancement

#945 Group Absinthe GraphQL requests by operation name
  .changesets/report-graphql-operation-name-as-absinthe-action-name.md
  lib/appsignal/absinthe.ex
  test/appsignal/absinthe_test.exs
Labels: enhancement

#946 Notify changelog repository of new releases
  .github/workflows/create_release_from_tag.yml
Labels: dev happiness

#947 Lock credo to 1.7.6 on Elixir < 1.13
  mix.exs
Labels: chore

#948 Don't run the installation script on windows
  .changesets/don-t-run-the-insallation-script-on-windows.md
  lib/mix/tasks/appsignal.install.ex
Labels: support, chore

#951 Ignore binwrite error response handling warning
  dialyzer.ignore-warnings
Labels: bug, dev happiness
