Repository appsignal/appsignal-elixir, pull requests merged in 2024-01, with the labels that each got.

#908 Fix Credo issue about function naming
  test/appsignal/nif_test.exs
  test/support/utils.ex
Labels: chore

#910 Bump agent to bfe19b1
  .changesets/remove-deprecated-extension-functions.md
  .changesets/update-probes-0.5.4.md
  agent.exs
Labels: enhancement

#911 Sample data fixes for lists and keyword lists
  .changesets/fix-data-encoding-for-keyword-lists.md
  .changesets/support-lists-as-root-sample-data.md
  lib/appsignal/span.ex
  lib/appsignal/utils/data_encoder.ex
  test/appsignal/span_test.exs
  test/appsignal/utils/data_encoder_test.exs
Labels: bug

#912 Fix flickering assertion on map keys
  test/mix/tasks/appsignal_diagnose_test.exs
Labels: chore

#915 Fix Ecto parallel preloads
  .changesets/add-appsignal-ecto-repo-to-fix-parallel-preloads.md
  config/config.exs
  lib/appsignal/ecto.ex
  lib/appsignal/ecto_repo.ex
  test/appsignal/ecto_repo_test.exs
  test/appsignal/ecto_test.exs
  test/support/fake_ecto_repo.ex
Labels: enhancement
