Repository appsignal/appsignal-elixir, pull requests merged in 2025-03, with the labels that each got.

#983 Switch Hackney to Finch
  .changesets/switch-hackney-with-finch.md
  .changesets/switch-the-internal-http-client--hackney--with-finch.md
  lib/appsignal.ex
  lib/appsignal/check_in/scheduler.ex
  lib/appsignal/diagnose/report.ex
  lib/appsignal/finch.ex
  lib/appsignal/transmitter.ex
  lib/appsignal/utils/push_api_key_validator.ex
  lib/mix/tasks/appsignal.diagnose.ex
  mix.exs
  mix_helpers.exs
  test/appsignal/diagnose/report_test.exs
  test/appsignal/finch_test.exs
  test/appsignal/transmitter_test.exs
  test/support/appsignal/fake_transmitter.ex
  test/support/fake_finch.ex
  test/support/fake_hackney.ex
Labels: enhancement

#986 Remove extra changeset
  .changesets/switch-the-internal-http-client--hackney--with-finch.md
Labels: chore

#989 Fix Finch usage in check-in scheduler
  .changesets/fix-check-in-scheduler.md
  lib/appsignal/check_in/scheduler.ex
  lib/appsignal/transmitter.ex
  lib/appsignal/utils/push_api_key_validator.ex
  test/appsignal/check_in/scheduler_test.exs
  test/support/appsignal/fake_transmitter.ex
Labels: bug

#990 Do not crash on non-printable errors
  .changesets/fix-crashes-when-failing-to-send-check-ins.md
  lib/appsignal/check_in/scheduler.ex
  lib/mix/tasks/appsignal.diagnose.ex
  test/appsignal/check_in/scheduler_test.exs
  test/mix/tasks/appsignal_diagnose_test.exs
Labels: bug

#991 Add mix appsignal.check_install task
  .changesets/add-mix-task-to-check-the-extension-install.md
  lib/appsignal/utils/tasks.ex
  lib/mix/tasks/appsignal.check_install.ex
  test/mix/tasks/appsignal_check_install_test.exs
Labels: enhancement
